version: "3.8"

networks:
  anonymization_network:
    driver: bridge
  pulsar_shared_network:
    external: true

services:
  # PostgreSQL
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anonymization_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - anonymization_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d anonymization_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Pulsar
  # pulsar:
  #   image: apachepulsar/pulsar:latest
  #   ports:
  #     - "6650:6650"
  #     - "8080:8080"
  #   networks:
  #     - anonymization_network
  #   command: bin/pulsar standalone

  # # Pulsar Express
  # pulsar-express:
  #   image: bbonnin/pulsar-express:latest
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     PE_CONNECTION_URL: "http://pulsar:8080"
  #   depends_on:
  #     - pulsar
  #   networks:
  #     - anonymization_network

  # FastAPI Anonymization Service
  anonymization-api:
    build:
      context: .
      dockerfile: anonymization.Dockerfile
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/anonymization_db
      PULSAR_HOST: pulsar
      API_HOST: 0.0.0.0
      API_PORT: 8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - anonymization_network
      - pulsar_shared_network
    volumes:
      - ./src:/app/src
    command: uvicorn src.anonymization_service.main:app --reload --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
    driver: local
